name: Sync to Hugging Face

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # <-- this is the fix

      - name: Set up Git LFS
        run: |
          git lfs install

      - name: Push to Hugging Face
        run: |
          git config --global user.email "operations@pdap.io"
          git config --global user.name "Sync to Hugging Face GitHub Action"
          git remote add hf https://PDAP:${HF_TOKEN}@huggingface.co/PDAP/inference_prototype_test
          git push hf main --force
