name: Sync to Hugging Face

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Bot"
          git remote add hf https://PDAP:${HF_TOKEN}@huggingface.co/PDAP/inference_prototype_test
          git push hf main
